springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-query-params-without-oauth2: true
    disable-swagger-default-url: true
    operationsSorter: method
  api-docs:
    path: /api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

externalUrl: https://github.com/Noti-iOS/noti-backend/wiki